### PR TITLE
Fix lagging behind by one character during live update for first tag 

### PR DESCRIPTION
**Pull request by mikemaccana**
Also fix the unnecessarily specific selection as mentioned in Gitter

### CODE REVIEW

**Comment by mikemaccana** [comment]
Now fixes #4 too. See comments in commit.

**Comment by developit** [comment]
Mike, 

Can you rebase this off of `master`? I actually made some modifications last night, addressing the two issues you mentioned here, but not the height bug.  Do you have a JSFiddle showing the height bug?

**Comment by mikemaccana** [comment]
Will do re: rebase. 

Let me see re: jsfiddle. I can replicate it here fairly easily...

**Comment by developit** [comment]
You should just be able to fork the one linked from the readme: http://jsfiddle.net/developit/d5w4jpxq/.  I suspect the issue might be related to this PR removing the `!important` postfix from the internal input field. It would be difficult to guarantee the application of those styles without `!important`, since they are affected by the rest of the page.  A shadow DOM implementation wouldn't have to worry about that, but I needed this one to work in older browsers where shadowDOM is difficult to polyfill.

**Comment by mikemaccana** [comment]
it was happening before I removed important - the issue was that, since checking if the tag needed to be added and adding the tag element were the same (in addTag()), the tag would be added before width() ran. Between the time addTag() was ran, and before width(), the tag input would look like the screenshot. I'll see if I can get the jsfiddle to repeat the same behaviour (0.6 still does).

**Comment by mikemaccana** [comment]
Need to make a fork with debugger to load in jsfiddle, and have a couple of other things to take care of first... 
screen shot 2015-02-23 at 14 40 25

**Comment by mikemaccana** [comment]
Lagging behind by one char is already fixed on 0.6
Extra height was my SCSS.
Please ignore this pull request, looks like 0.6 is golden!

**Pull request closed without merging**
